@startuml
skinparam linetype ortho
skinparam nodesep 100
skinparam ranksep 100

hide empty methods
hide empty attributes

entity Job <<models>>
entity Fleet <<models>>

entity Result <<models>>

abstract class Algorithm <<algorithms>>

class MilpAlgorithm <<algorithms>>

abstract class LinearModel <<algorithms>>
class ThreeIndexLinearModel <<algorithms>>

class InsertionAlgorithm <<algorithms>>

class InsertionIterator <<algorithms>>
class RankingInsertionIterator <<algorithms>>
class StatelessInsertionIterator <<algorithms>>

class InsertionStrategy <<algorithms>>
class IntensiveInsertionStrategy <<algorithms>>
class SamplingInsertionStrategy <<algorithms>>
class TailInsertionStrategy <<algorithms>>

class LocalSearchAlgorithm <<algorithms>>

abstract class LocalSearchStrategy <<algorithms>>
class ReallocationLocalSearchStrategy <<algorithms>>
class OneShiftLocalSearchStrategy <<algorithms>>
class TwoOPTLocalSearchStrategy <<algorithms>>

class GRASPAlgorithm <<algorithms>>
class IterativeAlgorithm <<algorithms>>
class SequentialAlgorithm <<algorithms>>


InsertionAlgorithm -up-|> Algorithm
Algorithm <|- MilpAlgorithm
Algorithm <|-- LocalSearchAlgorithm
Algorithm <|-- GRASPAlgorithm
Algorithm <|- IterativeAlgorithm
Algorithm <|-- SequentialAlgorithm


InsertionStrategy <|-- IntensiveInsertionStrategy
InsertionStrategy <|-- SamplingInsertionStrategy
InsertionStrategy <|-- TailInsertionStrategy

InsertionIterator <|-- RankingInsertionIterator
InsertionIterator <|-- StatelessInsertionIterator

LinearModel <|-- ThreeIndexLinearModel

LocalSearchStrategy <|-- ReallocationLocalSearchStrategy
LocalSearchStrategy <|-- OneShiftLocalSearchStrategy
LocalSearchStrategy <|-- TwoOPTLocalSearchStrategy


InsertionAlgorithm -left- InsertionIterator
InsertionAlgorithm -down- InsertionStrategy

MilpAlgorithm -- LinearModel

LocalSearchAlgorithm -- LocalSearchStrategy


GRASPAlgorithm -- LocalSearchAlgorithm
GRASPAlgorithm -- InsertionAlgorithm


note "composed of" as N1
N1 --o IterativeAlgorithm
N1 - Algorithm

note "composed of" as N2
N2 --o SequentialAlgorithm
N2 - Algorithm


Job "receives "--o Algorithm
Fleet "receives"--o Algorithm
Result "generates"-- Algorithm

@enduml

